development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:a82aec0d35347046c769981b22192aeb@scat.redistogo.com:10673/
  channel_prefix: message_me_production
